background_opacity 0.85
font_size 12.0
font_family FiraCode Nerd Font
window_padding_width 10

confirm_os_window_close -1

# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME
