# HyprEmoji Configuration

# Keybind to open hypremoji
bind = SUPER, period, exec, hypremoji

# Window rules for HyprEmoji
windowrule = float true, match:title ^(HyprEmoji)$ 
windowrule = move -172 627, match:title ^(HyprEmoji)$
windowrule = size 640 340, match:title ^(HyprEmoji)$