background       = 0xFF1a1b26
base             = 0xFF24283b
alternate_base   = 0xFF1f2335
text             = 0xFFc0caf5
bright_text      = 0xFFffffff
accent           = 0xFF7aa2f7
accent_secondary = 0xFFbb9af7

font_size        = 13
small_font_size  = 11
h1_size          = 20
h2_size          = 16
h3_size          = 14

icon_theme       = Papirus-Dark
