font=CaskaydiaCove Nerd Font:size=12
prompt="❯ "
layer=overlay
width=38
lines=18
horizontal-pad=12
vertical-pad=12
inner-pad=8
terminal=kitty
icons-enabled=yes
# icon-theme=Papirus-Dark

[colors]
# Theme: Tokyo Night Dark (Purple Accent)
background=1a1b26f5
text=c0caf5ff
prompt=bb9af7ff
placeholder=565f89ff
input=c0caf5ff
match=bb9af7ff
selection=7f42f0ff
selection-text=c0caf5ff
selection-match=bb9af7ff
counter=565f89ff
border=bb9af7ff

[border]
width=3
radius=10
