auto_wrap_with_terminal = true
command_install = 'paru -S %VALUE%'
command_remove = 'paru -R %VALUE%'

[Config]
hide_from_providerlist = false
icon = 'applications-internet'
min_score = 20
# name_pretty = 'Arch Packages'
